#指定激活环境
spring:
  profiles:
    active: dev

#数据库连接配置
  datasource:
    type: ${datasource.type}
    driver-class-name: ${datasource.driver-class-name}
    url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${datasource.username}
    password: ${datasource.password}

  #集成Swagger高版本启动异常配置，低版本可以不配置
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    #  # 数据库索引
    #  database: 0
    #  # 密码
    #  password:
    #  # 连接超时时间
    #  timeout: 180s
    # 使用lettuce链接方式
    lettuce:
      pool:
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: github.com.tang.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    github:
      com:
        tang:
          mapper: debug
          service: info
          controller: info

#jwt配置
jwt:
  # 设置jwt签名加密时使用的秘钥
  admin-secret-key: hui20-hub
  # 设置jwt过期时间
  admin-ttl: 7200000
  # 设置前端传递过来的令牌名称
  admin-token-name: token
  user-secret-key: tang
  user-ttl: 7200000
  user-token-name: authentication
alioss:
  endpoint: ${alioss.endpoint}
  access-key-id: ${alioss.access-key-id}
  access-key-secret: ${alioss.access-key-secret}
  bucket-name: ${alioss.bucket-name}
wechat:
  appid: ${wechat.appid}
  secret: ${wechat.secret}
  mchid : ${wechat.mchid}
  mchSerialNo: ${wechat.mchSerialNo}
  privateKeyFilePath: ${wechat.privateKeyFilePath}
  apiV3Key: ${wechat.apiV3Key}
  weChatPayCertFilePath: ${wechat.weChatPayCertFilePath}
  notifyUrl: ${wechat.notifyUrl}
  refundNotifyUrl: ${wechat.refundNotifyUrl}
shop:
  address: 北京市海淀区上地十街10号
baidu:
  ak: your-ak

  #配置热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: github.com.tang

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: hui20-hub
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
